name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version using Node.js 16+

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version using Node.js 16+
        with:
          node-version: '20'  # You can change this to '20' if you prefer Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t devops-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Local VMware VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker stop devops-app || true
            docker rm devops-app || true
            docker run -d -p 3000:3000 --name devops-app devops-app

